---
title: "Tree with heatmap"
author: "enrico frigoli"
date: '2022-04-10'
output:
  github_document:
    toc: true
---

```{r}
library(ggplot2)
library(ggtree)
```

DISCLAIMER: this code was written in few hours due to time constraints, starting from scratch, with the only purpose of obtaining the trees and the heatmaps to be inserted in the report. 


```{r}
bin_metadata <- read.csv('pathTo/SGB14797_bin_data.tsv', sep = '\t')
samples <- read.csv('pathTo/SGB14797_metadata.tsv', sep = '\t')
```

```{r}
##########################################
### Create my new metadata
##########################################

extr_bins <- bin_metadata[,1:2] # extract needed data from bin metadata

colnames(extr_bins) <- c('name', 'sampleID')

extr_sample <- samples[, c(2,5,7,9,10,11,20)] # extract needed data from sample metadata

extr_sample <- rbind(extr_sample, c('GCA_011405655.fna', 'reference genome', NA))  # manual addition of infos
extr_sample <- rbind(extr_sample, c("GCA_009755265.fna", 'reference genome', NA))  # manual addition of infos


final <- dplyr::left_join(extr_bins, extr_sample, by = "sampleID")    # join


tree <- read.tree('pathTo/core_gene.tre')       # read tree


final[order(final$name),]      # sort by name, since sample names must match leaf label in the tree
filenames <- tree$tip.label     # extract filenames from tree tips
filenames <- sort(filenames)
print(filenames)
final <- cbind(filenames, final)  # add filenames to ensure the match between tip.label and the metadata (the order doesn't matter)

row.names(final) <- final$filenames  # row names must match tip.label for data to be plot in the heatmap

final[is.na(final)] <- 'unknown'   # remove na
final$non_westernized[final$non_westernized == 'N'] <- 'no'    # homogenize values
final
```



```{r}
############## Build tree

final_tree <- ggtree(tree,
       layout = "rectangular") %<+% final +    # links your metadata to the graph
     geom_tiplab(aes(label = label), offset = 0.001) +               
     #geom_tiplab2(aes(label = study_condition)) +
     geom_tippoint(aes(color = country))
final_tree


p1 <- gheatmap(final_tree, final[,c(4,8)],          # select data to plot in the heatmap
         offset = 0.07,         # distance of heatmap from tree tips
         width = 0.1,           # the width of the heatmap
         font.size = 3,         # the font size of the column headers
         colnames_position = 'top',
         colnames_angle = 90,
         custom_column_labels = c('disease', 'non_westernized'),
         legend_title = 'Disease and NW')
p1

final$age <- as.numeric(final$age)
final$BMI <- as.numeric(final$BMI)

library(ggnewscale)   # add the second heatmap with cotinuous values
p2 <- p1 + new_scale_fill()
gheatmap(p2, final[,c(5,9)], offset=0.078, width=.1, colnames_position = 'top',
         colnames_angle=90, colnames_offset_y = .25, font.size = 3) +
    scale_fill_viridis_c(option="B", name="Age & BMI")

ggsave('myTree.png') 

```


